name: azuro
contracts:
  - name: Corev2
    handler: src/v2/core.ts
    events:
      - event: ConditionCreated(uint256 indexed gameId, uint256 indexed conditionId)
      - event: ConditionResolved(uint256 indexed conditionId, uint8 state, uint64 outcomeWin, int128 lpProfit)
      - event: ConditionStopped(uint256 indexed conditionId, bool flag)
      - event: NewBet(address indexed  bettor, address indexed affiliate, uint256 indexed conditionId, uint256 tokenId, uint64 outcomeId, uint128 amount, uint64 odds, uint128[2] funds)
      - event: OddsChanged(uint256 indexed conditionId, uint64[2] newOdds)
  - name: Expressv2
    handler: src/v2/express.ts
    events:
      - event: NewBet(address indexed bettor, uint256 indexed betId,(address,uint64,uint128,uint48,bool,(uint256,uint64)[] ,uint64[]) bet) # interesting stress test - struct within struct event emit
      - event: Transfer(address indexed from, address indexed to, uint256 indexed tokenId)
  - name: Corev3
    handler: src/v3/core.ts
    events:
      - event: ConditionCreated(uint256 indexed gameId, uint256 indexed conditionId, uint64[] outcomes)
      - event: ConditionResolved(uint256 indexed conditionId, uint8 state, uint64[] winningOutcomes, int128 lpProfit)
      - event: ConditionStopped(uint256 indexed conditionId, bool flag)
      - event: NewBet( address indexed bettor,  address indexed affiliate, uint256 indexed conditionId, uint256 tokenId, uint64 outcomeId, uint128 amount, uint256 odds, uint128[] funds)
      - event: OddsChanged(uint256 indexed conditionId, uint256[] newOdds)
      - event: MarginChanged(uint256 indexed conditionId, uint64 newMargin)
      - event: ReinforcementChanged(uint256 indexed conditionId, uint128 newReinforcement)
  - name: Expressv3
    handler: src/v3/express.ts
    events:
      - event: NewBet( address indexed bettor, uint256 indexed betId, (address,uint64,uint128,uint48,bool,(uint256,uint64)[] ,uint64[]) bet)
      - event: Transfer( address indexed from,  address indexed to, uint256 indexed tokenId)
  - name: FreeBetv3
    handler: src/v3/freebet.ts
    events:
      - event: NewBet(uint256 indexed freeBetId,address indexed core,address indexed bettor,uint256 azuroBetId,uint128 amount,uint64 minOdds,uint64 expiresAt)
      - event: BettorWin(address indexed core,address indexed bettor,uint256 indexed freeBetId,uint256 amount)
      - event: PayoutsResolved(uint256[] azuroBetId)
  - name: LiveCorev1
    handler: src/livecore/livecore.ts
    events:
      - event: ConditionCreated(uint256 indexed gameId, uint256 indexed conditionId, uint64[] outcomes, uint256[] odds, uint8 winningOutcomesCount)
      - event: ConditionResolved(uint256 indexed conditionId, uint8 state, uint64[] winningOutcomes, int128 lpProfit, uint64 settledAt)
      - event: NewLiveBet( address indexed bettor,  address indexed affiliate, uint256 indexed conditionId, uint256 tokenId, uint64 outcomeId, uint128 amount, uint64 odds, uint128 payoutLimit)
networks:
  - id: 100
    start_block: 0
    contracts:
      - name: Core
        address:
          - 0x4fE6A9e47db94a9b2a4FfeDE8db1602FD1fdd37d
        handler: src/v1/core.ts
        events:
          - event: ConditionCreated(uint256 indexed oracleConditionId, uint256 indexed conditionId, uint64 timestamp)
          - event: ConditionResolved(uint256 indexed oracleConditionId, uint256 indexed conditionId, uint64 outcomeWin, uint8 state, uint256 amountForLp)
          - event: ConditionShifted(uint256 oracleCondId, uint256 conditionId, uint64 newTimestamp)
          - event: ConditionStopped(uint256 indexed conditionId, bool flag)
          - event: LpChanged(address indexed newLp)
      - name: XYZFreeBet
        address:
          - 0xf0A93Ad0184cF1e5f29d7b5579358C99b9010F17
        handler: src/v1/freebet.ts
        events:
          - event: BettorWin(address bettor, uint256 azuroBetId, uint128 amount)
          - event: FreeBetMinted(address indexed receiver, uint256 indexed id, (uint128,uint64,uint64) bet)
          - event: FreeBetMintedBatch(address[] receivers, uint256[] ids, (uint128,uint64,uint64)[] bets)
          - event: FreeBetRedeemed(address indexed bettor, uint256 indexed id, uint256 indexed azuroBetId, uint128 amount)
          - event: FreeBetReissued(address indexed receiver, uint256 indexed id, (uint128,uint64,uint64) bet)
          - event: Transfer(address indexed from, address indexed to, uint256 indexed tokenId)
      - name: LP # TODO: This contract is templated, and should be generated dynamically using the dynamic contract registry https://docs.envio.dev/docs/dynamic-contracts
        address:
          - 0xac004b512c33D029cf23ABf04513f1f380B3FD0a
        handler: src/v1/lp.ts
        events:
          - event: BetterWin(address indexed better, uint256 tokenId, uint256 amount)
          - event: LiquidityAdded(address indexed account, uint256 amount, uint48 leaf)
          - event: LiquidityRemoved(address indexed account, uint48 indexed leaf, uint256 amount)
          - event: LiquidityRequested(address indexed requestWallet, uint256 requestedValueLp)
          - event: NewBet(address indexed owner, uint256 indexed betId, uint256 indexed conditionId, uint64 outcomeId, uint128 amount, uint256 odds, uint128 fund1, uint128 fund2)
          - event: Transfer(address indexed from, address indexed to, uint256 indexed tokenId)
          - event: WithdrawTimeoutChanged(uint64 newWithdrawTimeout)
      - name: Azurobets # TODO: This contract is templated, and should be generated dynamically using the dynamic contract registry https://docs.envio.dev/docs/dynamic-contracts
        address:
          - 0xFd9E5A2A1bfc8B57A288A3e12E2c601b0Cc7e476 # v1
          - 0xA3A1B460c68dc91c5B3f71f5487A76fac42858bf # v2
          - 0x313c2ac3d997c31732933d2eb73a335144b9c938 # v3
        handler: src/v1/azurobets.ts
        events:
          - event: Transfer(address indexed from, address indexed to, uint256 indexed tokenId)
      - name: Factory
        address:
          - 0x8EA1a7241537F10fa73363FDC6380F3FC8619c03
        handler: src/v2/factory.ts
        events:
          - event: NewCore(address indexed lp, address indexed core, string indexed coreType)
          - event: NewPool(address indexed lp, address indexed core, string indexed coreType, address access)
      - name: FreeBet
        address:
          - 0xB425E555492eE36c5A2918481EbbcF04AE73682b
        handler: src/v2/freebet.ts
        events:
          - event: BettorWin(address indexed core, address indexed bettor, uint256 indexed azuroBetId, uint128 amount)
          - event: FreeBetMinted(address indexed receiver, uint256 indexed id, (uint128,uint64,uint64) bet)
          - event: FreeBetMintedBatch(address[] receivers, uint256[] ids, (uint128,uint64,uint64)[] bets)
          - event: FreeBetRedeemed(address indexed core, address indexed bettor, uint256 indexed id, uint256 azuroBetId, uint128 amount)
          - event: FreeBetReissued(address indexed receiver, uint256 indexed id, (uint128,uint64,uint64) bet)
          - event: Transfer(address indexed from, address indexed to, uint256 indexed tokenId)
      - name: LPv2 # TODO: This contract is templated, and should be generated dynamically using the dynamic contract registry https://docs.envio.dev/docs/dynamic-contracts
        address:
          - 0x204e7371Ade792c5C006fb52711c50a7efC843ed # implementation 0xC9A714a953015a4DBCD3B016e782100C291032F0
        handler: src/v2/lp.ts
        events:
          - event: BettorWin(address indexed core, address indexed bettor, uint256 tokenId, uint256 amount)
          - event: GameCanceled(uint256 indexed gameId)
          - event: GameShifted(uint256 indexed gameId, uint64 newStart)
          - event: LiquidityAdded(address indexed account, uint48 indexed depositId, uint256 amount)
          - event: LiquidityDonated(address indexed account, uint48 indexed depositId, uint256 amount)
          - event: LiquidityManagerChanged(address newLiquidityManager)
          - event: LiquidityRemoved(address indexed account, uint48 indexed depositId, uint256 amount)
          - event: NewGame(uint256 indexed gameId, uint64 startsAt, bytes data) # TODO: This only imported v3 not v2 version which seems to be the same contract
          - event: Transfer(address indexed from, address indexed to, uint256 indexed tokenId)
          - event: WithdrawTimeoutChanged(uint64 newWithdrawTimeout)
      - name: Corev2
      - name: Expressv2
      - name: FreeBetFactory
        address:
          - 0x00a7629689073BF8F343DE80FBbC34425131b3e5
        handler: src/v3/freebetFactory.ts
        events:
          - event: NewFreeBet(address indexed freeBetAddress, address indexed lpAddress, address affiliate, address manager)
      - name: Corev3
      - name: Expressv3
      - name: FreeBetv3
      - name: LiveCorev1
# template contracts

# LP 0xac004b512c33d029cf23abf04513f1f380b3fd0a LPV1
# LP 0xC9A714a953015a4DBCD3B016e782100C291032F0 LPv2 implementation (proxy 0x204e7371Ade792c5C006fb52711c50a7efC843ed todo)

# Azuro bet NFT 0xFd9E5A2A1bfc8B57A288A3e12E2c601b0Cc7e476 v1
# Azuro bet NFT 0xA3A1B460c68dc91c5B3f71f5487A76fac42858bf v2 (implementation 0x44Cf666D3CEd2C182c6dAE0582b1854467FAeB20)
# Azuro bet NFT 0x313c2ac3d997c31732933d2eb73a335144b9c938 v3 (implementation 0x44Cf666D3CEd2C182c6dAE0582b1854467FAeB20)

# Freebet contracts - 0x18efca50914e44b17e62fbc866a7e597c435a2be // checksum
# Freebet contracts - 0x31339074aa3f84ebaf15352e3ff6453831daad63 // checksum
# Freebet contracts - 0x554097c51656a4546c2b4aae492154cae7a07834 // checksum
# Freebet contracts - 0x87c05de2f47e95bcea59f828431d31e583309b40 // checksum
# Freebet contracts - 0xac2476db1fd2f3e7d1da7ccc3fac7d1bd1c4b5a2 // checksum
# Freebet contracts - 0xac3ba36b3bceb78192d06d95dfca4eab891f1550 // checksum
# Freebet contracts - 0xb425e555492ee36c5a2918481ebbcf04ae73682b // checksum // FreeBet
# Freebet contracts - 0xd485e2b49563b3ba7b3ca6770ed1c67856e34a16 // checksum
# Freebet contracts - 0xf0a93ad0184cf1e5f29d7b5579358c99b9010f17 // checksum // XYZFreeBet

# Core contracts - 0x4ee3923484dfdc7ea2f1c558c2c820a97a727636 // checksum
# Core contracts - 0x4fe6a9e47db94a9b2a4ffede8db1602fd1fdd37d // checksum // Core
# Core contracts - 0x7f3f3f19c4e4015fd9db2f22e653c766154091ef // checksum
# Core contracts - 0xc95c831c7bdb0650b8cd5f2a542b263872d8ed0e // checksum
# Core contracts - 0xdbc3be2ddb53e1a288f7b7a4d020f8056d3b0f7c // checksum
